// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTFZ6fXWmR_P4yvw4WZGZS_EIW-CnGNSE',
    appId: '1:1008249357340:web:b0041639fee67aa570cbd9',
    messagingSenderId: '1008249357340',
    projectId: 'sakinaacademy-72d85',
    authDomain: 'sakinaacademy-72d85.firebaseapp.com',
    storageBucket: 'sakinaacademy-72d85.firebasestorage.app',
    measurementId: 'G-57HWLQL2VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUqY3CtwZ0TmAJTLUiQAdVPcwzcGNKuo',
    appId: '1:1008249357340:android:ec908a592643ecf770cbd9',
    messagingSenderId: '1008249357340',
    projectId: 'sakinaacademy-72d85',
    storageBucket: 'sakinaacademy-72d85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAorOBJ4XWjZwvoyNSnGdj7S_gbT25SRqo',
    appId: '1:1008249357340:ios:bb84730cfaa0ceb470cbd9',
    messagingSenderId: '1008249357340',
    projectId: 'sakinaacademy-72d85',
    storageBucket: 'sakinaacademy-72d85.firebasestorage.app',
    iosBundleId: 'com.sakinaacademy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAorOBJ4XWjZwvoyNSnGdj7S_gbT25SRqo',
    appId: '1:1008249357340:ios:d6730053a9322f3970cbd9',
    messagingSenderId: '1008249357340',
    projectId: 'sakinaacademy-72d85',
    storageBucket: 'sakinaacademy-72d85.firebasestorage.app',
    iosBundleId: 'com.example.sakinaAc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Ojv4xtHaPMy_5Q8C6aqyqhDJi0EyOd4',
    appId: '1:1008249357340:web:9994c575295df7ec70cbd9',
    messagingSenderId: '1008249357340',
    projectId: 'sakinaacademy-72d85',
    authDomain: 'sakinaacademy-72d85.firebaseapp.com',
    storageBucket: 'sakinaacademy-72d85.firebasestorage.app',
    measurementId: 'G-2ZPX6027J8',
  );

}